# Generated by Django 3.2.7 on 2021-10-22 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=280)),
                ('author', models.ForeignKey(on_delete=models.SET(network.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=models.SET(network.models.get_sentinel_user), to='network.post')),
                ('user', models.ForeignKey(on_delete=models.SET(network.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=models.SET(network.models.get_sentinel_user), related_name='followed', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=models.SET(network.models.get_sentinel_user), related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('follower', django.db.models.expressions.F('followed')), _negated=True), name='users_cannot_follow_themselves'),
        ),
    ]
